###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
   application:
        name: yxw-api-member

   redis:
      host: 192.168.162.130
      password:
      port: 6379
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  ###数据库相关连接
   main:
       allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
   datasource:
       name: yxw_member
       url: jdbc:mysql://118.31.9.5:3306/yxw_member
       username: niping
       password: 123456
       tomcat-jdbc: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
       filters: stat
       maxActive: 20
       initialSize: 1
       maxWait: 60000
       minIdle: 1
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       poolPreparedStatements: true
       maxOpenPreparedStatements: 20

mybatis:
 mapper-locations: classpath:mapping/*.xml
 type-aliases-package: com.yxw.member.entity


###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka


####swagger相关配置
swagger:
  base-package: com.yxw.member.service
  title: 会员服务接口文档
  description:
  version: 1.0
  terms-of-service-url: www.yxw.com
  contact:
    name: niping
    email: niping0020@163.com



